id: P004339
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1235
  title: འོད་ཟེར་དྲི་མེད་ཀྱི་འཆི་བསླུའི་ཆོ་ག
  author: ''
  volumes:
    55fec9723ae14756b39f413a110e23f6:
      image_group_id: I1CZ1711
      title: ''
      volume_number: 1
      total_pages: 34
